import { featuresSettings, AppSettings } from './app.config';

export interface FareStructure {
    isShow: Boolean;
    label: string; // Label Field
    value: string; // Value Field
    ref: string; // Key: Value
    unit: string; // unit - KM, Rs.
    currency: string;
    type: string; // (KMRATE / FLATRATE) Label in distance
    typeValue: string; // Value For Type
    sideValLabel: string; // Side Label For Key Field.
    sideVal: string; // Value For Side Label
    sideValUnit: string; // Unit For Side Value
}

export class FareInvoiceDetails {
    public static availableFare: Array<FareStructure> = [
        {
            isShow: true,
            label: 'Total Distance',
            value: '0.00',
            ref: 'distance',
            unit: featuresSettings.distanceUnit,
            currency: '',
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        {
            isShow: true,

            label: 'Estimated Time',
            value: '0 Mins',
            ref: 'timeLable',
            unit: '',
            currency: '',
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        {
            isShow: true,
            label: 'Base  Fee',
            value: '0.00',
            ref: 'BaseFare',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        {
            isShow: true,
            label: 'Booking  Fee',
            value: '0.00',
            ref: 'bookingFare',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        {
            isShow: true,
            label: 'Minimum Fare',
            value: '0.00',
            ref: 'minFareAdded',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'minFare',
            sideVal: '0.00',
            sideValUnit: AppSettings.defaultcur,
        },
        {
            isShow: true,
            label: 'Distance Fare',
            value: '0.00',
            ref: 'KMFare',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'perMileRate',
            sideVal: '0.00',
            sideValUnit:
                AppSettings.defaultcur + '/' + featuresSettings.distanceUnit,
        },
        {
            isShow: true,
            label: 'Time Fare',
            value: '0.00',
            ref: 'travelFare',
            unit: '',
            type: '',
            currency: AppSettings.defaultcur,
            typeValue: '',
            sideValLabel: 'travelRate',
            sideVal: '0.00',
            sideValUnit: AppSettings.defaultcur + '/Min',
        },
        /*         {
                 label: 'Pickup Charge',
                 value: '0.00',
                 ref: 'pickupCharge',
                 unit: AppSettings.defaultcur,
                 type: '',
                 typeValue: '',
                 sideValLabel: '',
                 sideVal: '',
                 sideValUnit: ''
             }, */
        {
            isShow: true,
            label: 'Waiting Charge',
            value: '0.00',
            ref: 'waitingFare',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'waitingCharge',
            sideVal: '0.00',
            sideValUnit: AppSettings.defaultcur + '/Min',
        },
        {
            isShow: true,
            label: 'Promo Code',
            value: '0.00',
            ref: 'discountAmt',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'promoCode',
            sideVal: '',
            sideValUnit: '',
        },
        /*         {
                 label: 'Other Discount',
                 value: '0.00',
                 ref: 'DetuctedFare',
                 unit: AppSettings.defaultcur,
                 type: '',
                 typeValue: '',
                 sideValLabel: '',
                 sideVal: '',
                 sideValUnit: ''
             }, */
        {
            isShow: true,
            label: 'Tax Amount',
            value: '0.00',
            ref: 'tax',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'taxPercentage',
            sideVal: '0.00',
            sideValUnit: '%',
        },
        {
            isShow: true,
            label: 'Pickup Fee',
            value: '0.00',
            ref: 'pickupCharge',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'pickupCharge',
            sideVal: '0.00',
            sideValUnit: AppSettings.defaultcur,
        },
        {
            isShow: featuresSettings.isDTS,
            label: 'TDS Tax Amount',
            value: '0.00',
            ref: 'taxTDSPercentage',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: 'taxTDS',
            sideVal: '0.00',
            sideValUnit: '%',
        },
        // {
        //     label: 'Google Rate',
        //     value: '0.00',
        //     ref: 'googleRate',
        //     unit: '', currency: AppSettings.defaultcur,
        //     type: '',
        //     typeValue: '',
        //     sideValLabel: '',
        //     sideVal: '',
        //     sideValUnit: ''
        // },
        // {
        //     isShow: true,
        //     label: 'Call center Fee',
        //     value: '0.00',
        //     ref: 'callCenterFee',
        //     unit: '',
        //     currency: AppSettings.defaultcur,
        //     type: '',
        //     typeValue: '',
        //     sideValLabel: '',
        //     sideVal: '',
        //     sideValUnit: '',
        // },
        {
            isShow: true,
            label: 'Surge Percentage',
            value: '0',
            ref: 'surgePercent',
            unit: '%',
            currency: '',
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        {
            isShow: true,
            label: 'Surge Reason',
            value: 'N/A',
            ref: 'surgeLabel',
            unit: '',
            currency: '',
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        {
            isShow: true,
            label: 'Surge Amount',
            value: '0.00',
            ref: 'surgeAmt',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
        // {
        //     isShow: true,
        //     label: 'Gateway Charge',
        //     value: '0.00',
        //     ref: 'gatewayCharge',
        //     unit: '',
        //     currency: AppSettings.defaultcur,
        //     type: '',
        //     typeValue: '',
        //     sideValLabel: 'gatewayCharge',
        //     sideVal: '0.00',
        //     sideValUnit: '%',
        // },
        {
            isShow: true,
            label: 'Total Fare',
            value: '0.00',
            ref: 'totalFare',
            unit: '',
            currency: AppSettings.defaultcur,
            type: '',
            typeValue: '',
            sideValLabel: '',
            sideVal: '',
            sideValUnit: '',
        },
    ];
}
