apply plugin: 'com.android.application'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}


android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.soofer.driver"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 10
        versionName "2.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

    buildFeatures {
        buildConfig true
    }

    tasks.withType(JavaCompile).configureEach{
        options.fork = true
        options.forkOptions.jvmArgs +=[
                '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
                '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED',
                '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED']
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude '*/res/**'
        exclude 'AndroidManifest.xml'
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "StripeURL", '"https://connect.stripe.com/express/oauth/authorize?client_id="'
            buildConfigField "String", "StripeKey", '"ca_KdtdAYDtmTOFx32L6fnKrsvfdWcC0ZVK"'
            buildConfigField "String", "Stripe", '"pk_live_51JvLMsD9LszUmsLxvA3vVVqJPXPCncqNSqE2RTiWDqaj0TvQPXTtyG4OqopDu68z6GEMlhcdea0HkmXsdc7pWtXM00xVZJANuo"'
// live key

        }
        debug {
            buildConfigField "String", "StripeURL", '"https://connect.stripe.com/express/oauth/authorize?client_id="'
            buildConfigField "String", "StripeKey", '"ca_KdtdAYDtmTOFx32L6fnKrsvfdWcC0ZVK"'
            buildConfigField "String", "Stripe", '"pk_live_51JvLMsD9LszUmsLxvA3vVVqJPXPCncqNSqE2RTiWDqaj0TvQPXTtyG4OqopDu68z6GEMlhcdea0HkmXsdc7pWtXM00xVZJANuo"'
// test key
            // buildConfigField "String", "StripeKey", '"ca_FJQTO7h7cypG5XJd8hhRdJfymHpdAILG"' // live key

        }
    }
    bundle {
        language {
            // Specifies that the app bundle should not support
            // configuration APKs for language resources. These
            // resources are instead packaged with each base and
            // dynamic feature APK.
            enableSplit = false
        }
    }

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
    dataBinding{
        enabled true
    }

    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }

}
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.0'
            }
        }
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "https://maven.google.com" // Google's Maven repository
        }
        maven {
            url "https://dl.bintray.com/glomadrian/maven"
        }

    }
}
repositories {
    flatDir {
        dirs "libs"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.3.0'
    //cardview
    implementation 'androidx.cardview:cardview:1.0.0'
    //recycleview
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.dynamicanimation:dynamicanimation:1.0.0'
    implementation 'androidx.core:core:1.5.0'
    
    //rayzor pay
    implementation 'com.razorpay:checkout:1.5.16'


    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.firebase:firebase-crashlytics:18.2.12'
    implementation 'com.google.firebase:firebase-analytics:21.1.0'
    implementation 'com.google.firebase:firebase-crashlytics-ktx:18.3.0'
    implementation 'com.google.firebase:firebase-analytics-ktx:21.2.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    //multidex grdle
    implementation 'androidx.multidex:multidex:2.0.1'
    //dp and sp common grdle
    implementation 'com.intuit.sdp:sdp-android:1.0.6'
    //butternife gradle
    implementation 'com.jakewharton:butterknife:10.2.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.3'
    //material edittext
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    //google map gradl
    implementation 'com.google.android.gms:play-services-maps:17.0.1'
    implementation "com.google.android.gms:play-services-location:18.0.0"

    //retrofit gson convertor
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    //rx java
    implementation 'io.reactivex.rxjava3:rxjava:3.0.4'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava3:2.9.0'

    implementation ("com.squareup.okhttp3:okhttp:3.12.12"){
        force = true //API 19 support
    }
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.12'
    //ui validation gradle
    implementation 'com.mobsandgeeks:android-saripaar:2.0.3'
    //stripe
    implementation "com.stripe:stripe-java:5.7.1"
    //braintree card form
    implementation 'com.braintreepayments:card-form:4.2.0'

    //jwt decoder
    implementation 'com.auth0.android:jwtdecode:1.1.1'

    //request progress bar
    implementation 'com.mikhaellopez:circularprogressbar:1.1.1'

    //glide gradle
    implementation 'com.github.bumptech.glide:glide:3.7.0'

    //firebase and geofire
    implementation 'com.firebase:geofire-android:2.3.1'
    implementation 'com.google.firebase:firebase-core:19.0.0'
    implementation 'com.google.firebase:firebase-database:20.1.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
    //remote config
    implementation 'com.google.firebase:firebase-config:20.0.4'

    //google direction
    implementation 'com.akexorcist:googledirectionlibrary:1.1.1'
    implementation 'com.google.maps.android:android-maps-utils:0.6.2'

    //material datetime picker
    implementation 'com.wdullaer:materialdatetimepicker:4.2.3'

    //Circle image view
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    //country code picker
    implementation 'com.github.yesterselga:CountryPickerAndroid:1.0.0'

    //event bus
    implementation 'org.greenrobot:eventbus:3.2.0'

    //alert gradle
    implementation 'com.github.tapadoo:alerter:7.2.4'

    /*   //opt picker
    implementation 'com.github.stfalcon:smsverifycatcher:0.3.2'*/

    //latto loader
    implementation 'com.airbnb.android:lottie:3.0.0'

    implementation 'com.jakewharton.rxbinding:rxbinding:1.0.0'


    //font gradle
    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.0.3'


    //sms retriver
    implementation 'com.google.android.gms:play-services-base:17.6.0'
    implementation 'com.google.android.gms:play-services-identity:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:20.2.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:18.0.1'

    //mobile number
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.10.17'


    //material switch
   // implementation 'com.github.glomadrian:MaterialAnimatedSwitch:1.1@aar'

    //otp picker
    implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.1.0'

    //life cycle
    implementation 'androidx.lifecycle:lifecycle-runtime:2.3.1'
    //noinspection LifecycleAnnotationProcessorWithJava8
    annotationProcessor 'androidx.lifecycle:lifecycle-compiler:2.3.1'

    //shimmer textview
    implementation 'com.romainpiel.shimmer:library:1.4.0@aar'

    //zoomview
    implementation 'com.github.rahulkapoor1:ZommableLoadingImageView:v1.2'


    //stripe
    implementation 'com.stripe:stripe-android:2.0.2'

    implementation 'com.github.GwonHyeok:StickySwitch:0.0.16'


    //rxpermission
    implementation 'com.github.tbruyelle:rxpermissions:0.12'

    //Agora Voice Call
    implementation 'io.agora.rtc:voice-sdk:4.4.1'

    implementation 'com.google.firebase:firebase-crashlytics-buildtools:2.9.1'
    implementation 'com.google.firebase:firebase-crashlytics:18.4.0'
    implementation 'com.google.firebase:firebase-analytics:21.2.0'

    implementation "android.arch.work:work-runtime:1.0.1"
    implementation 'androidx.work:work-runtime:2.7.1'
    
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
