const configObj = {
  "secret": "abservetech",
  "adminsecret": "abservetech",
  "appMode": "prod",
  "port": "3001",
  "database": "rebustarv2server",
  "appName": "Sooffer",
  "resetPasswordTo": "Sooffer",
  "utcOffset": "-05:00",
  "gmtZone": "GMT+05:30",
  "phoneCode": "+1",
  "baseurl": "https://api.sooffer.com/",
  "fileurl": "https://api.sooffer.com/public/",
  "frontendurl": "https://sooffer.com/webadmin",
  "landingurl": "https://sooffer.com/",
  "applink": "https://appurl.io/",
  "shareTrip": "http:///18.220.141.188:3001/public/shareTrip/locater.html?tripId=",
  "project_id": "i-gateway-332311-default-rtdb",
  "firebasekey": {
    "appName": "i-gateway-332311-default-rtdb",
    "authDomain": "i-gateway-332311-default-rtdb.firebaseapp.com",
    "databaseURL": "https://i-gateway-332311-default-rtdb.firebaseio.com",
    "storageBucket": "i-gateway-332311-default-rtdb.appspot.com"
  },
  "googleApi": "AIzaSyAS_tlCrm2twqDOfN9R3wKS8u8jdmDfb6k",
  "AndroidDtaxiAPI": "AIzaSyC4Reycz36OmNMz048T9-E6YErfIRMABMg",
  "IOSDtaxiAPI": "AIzaSyA0Rw4sntPKrobxyiRNSgh4x31aK9MvIxo",
  "fcmServer": "AAAAGAksKio:APA91bFYOC9P4WlYu1cPpYko-PbohBdj0vFDvtPeiht0msz7uy6PXGM4sjoNchnGPuSVExQCcpzLXcPA_ByluhqLyhRlNR5_FYaH2CUtbzmZ3B7zdovvFtxpEnNYThcUOfPM-ntcy74k",
  "adminfcmServer": "AAAAGAksKio:APA91bFYOC9P4WlYu1cPpYko-PbohBdj0vFDvtPeiht0msz7uy6PXGM4sjoNchnGPuSVExQCcpzLXcPA_ByluhqLyhRlNR5_FYaH2CUtbzmZ3B7zdovvFtxpEnNYThcUOfPM-ntcy74k",
  "directionApi": "https://maps.googleapis.com/maps/api/directions/json?origin={from}&destination={to}&key={key}",
  "requestRadius": 30,
  "rentalRequestRadius": 5,
  "outstationRequestRadius": 10,
  "maxDistBtRiderAndDriver": 48270,
  "maxDistBtRiderAndDriverRental": 50000,
  "maxDistBtRiderAndDriverOutsation": 5000,
  "driversNeedToPickFromSurrounding": 5,
  "driversNeedToCallForATrip": 5,
  "requestTime": 60000,
  "requestTimeOutsation": 30000,
  "userCancelTime": 180000,
  "requestType": "onebyone",
  "onebyoneConfig": {
    "enable": false,
    "logic": "bubble",
    "incrementSteps": 5,
    "incrementTimes": 1
  },
  "lowRatingForUser": 1,
  "noOfDriverCancelAllowed": 5,
  "noOfRiderCancelAllowed": 10,
  "oldCancelBalanceRiderAllowed": 30,
  "rideLaterRemainder": 4,
  "rideLaterStart": 2,
  "upcomingRideLaterTimeBuffer": 30,
  "redtaxisettings": {
    "connectDailyTripBefore": 30,
    "connectRentalTripBefore": 30,
    "connectOutstationTripBefore": 30,
    "connectOutstationTripBeforeFirst": 60
  },
  "makeDriverOfflineAfterInactive": 3,
  "fcmpushDriverOfflineAfterInactive": 3,
  "emailGateway": "sendgrid",
  "smtpConfig": {
    "host": "smtp.gmail.com",
    "port": 465,
    "secure": true,
    "auth": {
      "user": "abservetech.smtp@gmail.com",
      "pass": "z{=6P*eaY(p(bKBb"
    },
    "sgAcessKey": "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"
  },
  "mailFrom": "\"Sooffer Admin \" <info@sooffer.com>",
  "supportNo": "8888208018",
  "smsGateway": {
    "smsGatewayName": "telynx",
    "twilioaccountSid": "",
    "twilioauthToken": "",
    "twilioNo": "",
    "nexmoapiKey": "",
    "nexmoapisecret": "",
    "nexmoapiNumber": "",
    "localAPIendpoint": "",
    "rahisiUsername": "",
    "rahisiPassword": "",
    "telnyxSecretKey": "KEY017D1B6ECC7B793F5E1E9B24172CC849_tKB1hdMfLF95KxZBl5ZOf6",
    "telnyxNo": "+16062129030"
  },
  "aws": {
    "config": {
      "accessKeyId": "AKIAQN7HEP76VY22VZP7",
      "secretAccessKey": "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",
      "region": "us-east-1"
    },
    "bucket": {
      "Bucket": "sooffer",
      "ContentType": "image/jpeg",
      "Body": {
        "fd": null,
        "path": "public/driverVehicle/fileFront-1713431389131.jpg",
        "flags": "r",
        "mode": 438,
        "end": null,
        "bytesRead": 460569,
        "closed": true,
        "_readableState": {
          "objectMode": false,
          "highWaterMark": 8388608,
          "buffer": {
            "head": null,
            "tail": null,
            "length": 0
          },
          "length": 0,
          "pipes": [],
          "flowing": false,
          "ended": true,
          "endEmitted": true,
          "reading": false,
          "constructed": true,
          "sync": false,
          "needReadable": false,
          "emittedReadable": false,
          "readableListening": true,
          "resumeScheduled": false,
          "errorEmitted": false,
          "emitClose": true,
          "autoDestroy": true,
          "destroyed": true,
          "errored": null,
          "closed": true,
          "closeEmitted": true,
          "defaultEncoding": "utf8",
          "awaitDrainWriters": null,
          "multiAwaitDrain": false,
          "readingMore": false,
          "dataEmitted": true,
          "decoder": null,
          "encoding": null
        },
        "_events": {},
        "_eventsCount": 3
      },
      "Key": "fileFront-1713431389131.jpg"
    }
  },
  "paymentGateway": {
    "paymentGatewayName": "stripe",
    "paymentGatewayCurrency": "USD",
    "clientId": "ca_KdtdPkQ2a4GPlVRxb3YscDNnAWRMcIAP",
    // "stripeSk": "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",
    // "stripePk": "pk_live_51JvLMsD9LszUmsLxvA3vVVqJPXPCncqNSqE2RTiWDqaj0TvQPXTtyG4OqopDu68z6GEMlhcdea0HkmXsdc7pWtXM00xVZJANuo",
    "stripeSk": "sk_test_51JvLMsD9LszUmsLx4C61Ibw6FRHvFyYYpT2LtEl468FgV9uqL4l6ExgVSeZwdMt2Xpe2MOkKBkKJkehYe7XqLACC00djxxYDrI",
    "stripePk": "pk_test_51JvLMsD9LszUmsLxMrARz8Aag0y5XeOMUnUNGzZ4oKfiyfSjnkGkGkntDJQvH3Z2nisIuNe1VsTGwJu5jPFIYljW008c1M23tQ",
    "stripeConnectAccountType": "express",
    "braintreeEnvironment": "Sandbox",
    "braintreeMerchantId": "c4qsnymzstrz64q7",
    "braintreePublicKey": "tg4c8x2vqkkq8hxx",
    "braintreePrivateKey": "39ec8e5f4bddbe7e736a8176c048d803",
    "paystackSecretKey": "sk_test_05178aebc83100fb6809004b3484e058fe015dd0",
    "paystackPublicKey": "pk_test_9009e19b68049e96a638e335366617aa11f8fcfa",
    "paytmMerchantKey": "",
    "razorpayId": "errtr5544gnj",
    "razorpaySecretKey": "njbjb14565ff",
    "razorpayAccountNumber": ""
  },
  "currency": "USD",
  "currencySymbol": "$",
  "distanceUnit": "Miles",
  "distanceSymbol": "Mi",
  "companyaddress": "PO Box 797231  Dallas TX 75379",
  "companymail": "info@sooffer.com",
  "querymail": "sooffer@gmail.com",
  "contactmail": "sooffercontact@gmail.com",
  "appDefaultLanguageCode": "en",
  "googleCharge": 0,
  "countryCode": "IN",
  "calculateZoneFare": true,
  "calculateZoneFareInEstimation": true,
  "neededOutstationFlow": true,
  "needRentalFlow": true,
  "isRiderEmailVerifyNeeded": true,
  "isDriverEmailVerifyNeeded": true,
  "tollGateDetails": {
    "url": "https://apis.tollguru.com/toll/v2/origin-destination-waypoints",
    "x-api-key": "nDRqmht8TqQghtgqfG4H8TNHrf78nM8p"
  }
};module.exports = configObj