const config = require('./config');  
const notifications = {
    defaultLanguage: config.appDefaultLanguageCode,
    en: {
        testMsg: `Hi, Test Push Notification From `,
        tripEnd: `Trip Ended`,
        driver: `Your Driver Has Arived`,
        tripstart: `Trip Started`,
        acceptScheduleRequest: `Driver Has Accepted Your Schedule Trip Request`,
        driverCancelScheduleTaxi: `Schedule Trip Cancelled By Driver`,
        userCancelScheduleTaxi: `Schedule Trip Cancelled By Rider`,
        acceptRequest: `Driver Has Accepted Your Trip Request`,
        requestTaxiRetry: `Trip Cancelled By Driver`,
        cancelCurrentTrip: `Trip Cancelled`,
        updateDropLocation: `Current Trip Drop Location Changed.`,
        sendSCHStartRequestToDrivers: `You already have One Scheduled Trip On this Time`,
        sendSCHStartAlertToRider: `You already have One Scheduled Trip On this Time`,
        sendnotification: `You have One Upcoming Scheduled Trip `,
        sendrequest: `Safe Taxi Request`,
        newquest: `New Request`,
        updateDriver: `New Request`,
        test: `RebuStar app`,
        verifyNumberRider: `Your OTP Verification Code for `,
        forgotPasswordRider: `Use This Code To reset Your Account Password From`,
        emergencyMsg: `is riding in has reached you because of some emergency, you can track his ride here`,
        resetpassword: `Your Password Has Been Reseted to Thank You.`,
        proofStatus: `Your Account was Activated. Thank You.`,
        rideLaterReceived: `Your Ride Later request received,we will assign Driver before Trip Time.`,
        inactivateIdelDriver: `Your app is now online.`,
        rideLaterNoResponse: `Your Scheduled Trip has cancelled due to Driver unavailablity, you can request later.`,
    },
    es: {
        testMsg: `Hola, prueba de notificación push de`,
        tripEnd: `Viaje terminado`,
        driver: `Su conductor ha llegado`,
        tripstart: `Viaje iniciado`,
        acceptScheduleRequest: `El conductor ha aceptado su solicitud de viaje programado`,
        acceptRequest: `El conductor ha aceptado su solicitud de viaje`,
        driverCancelScheduleTaxi: `Programar viaje cancelado por el conductor`,
        userCancelScheduleTaxi: `Programar viaje cancelado por jinete`,
        requestTaxiRetry: `Viaje cancelado por el conductor`,
        cancelCurrentTrip: `Viaje cancelado`,
        updateDropLocation: `Se modificó la ubicación actual de caída del viaje.`,
        sendSCHStartRequestToDrivers: `Tienes un viaje programado en este momento`,
        sendSCHStartAlertToRider: `Tienes un viaje programado en este momento`,
        sendnotification: `Tiene un próximo viaje programado en `,
        sendrequest: `Solicitud de taxi seguro`,
        newquest: `Nueva solicitud`,
        updateDriver: `Nueva solicitud`,
        test: `Aplicación RebuStar`,
        verifyNumberRider: `Su código de verificación de OTP para `,
        forgotPasswordRider: `Use este código para restablecer la contraseña de su cuenta`,
        emergencyMsg: `está viajando te ha alcanzado debido a alguna emergencia, puedes rastrear su viaje aquí`,
        resetpassword: `Su contraseña ha sido restablecida para agradecerle`,
        proofStatus: `Su cuenta fue activada. Gracias.`,
    },
    ta: {
        testMsg: `Hi, Test Push Notification From `,
        tripEnd: `பயணம் முடிந்தது`,
        driver: `Your Driver Has Arived`,
        tripstart: `Trip Started`,
        acceptScheduleRequest: `Driver Has Accepted Your Schedule Trip Request`,
        driverCancelScheduleTaxi: `Schedule Trip Cancelled By Driver`,
        userCancelScheduleTaxi: `திட்டமிடப்பட்ட பயணம்' ரைடரால் ரத்து செய்யப்பட்டது திட்டமிடப்பட்ட பயணம்`,
        acceptRequest: `Driver Has Accepted Your Trip Request`,
        requestTaxiRetry: `Trip Cancelled By Driver`,
        cancelCurrentTrip: `பயணம் ரத்து செய்யப்பட்டது`,
        updateDropLocation: `Current Trip Drop Location Changed.`,
        sendSCHStartRequestToDrivers: `இந்த நேரத்தில் உங்களுக்கு ஏற்கனவே ஒரு திட்டமிடப்பட்ட பயணம் உள்ளது`,
        sendSCHStartAlertToRider: `இந்த நேரத்தில் உங்களுக்கு ஏற்கனவே ஒரு திட்டமிடப்பட்ட பயணம் உள்ளது`,
        sendnotification: `வரவிருக்கும் ஒரு 'திட்டமிடப்பட்ட பயணம்' உள்ளது `,
        sendrequest: `Safe Taxi Request`,
        newquest: `புதிய கோரிக்கை`,
        updateDriver: `புதிய கோரிக்கை`,
        test: `RebuStar app`,
        verifyNumberRider: `உங்கள் OTP சரிபார்ப்புக் குறியீடு `,
        forgotPasswordRider: `உங்கள் கணக்கு கடவுச்சொல்லை மீட்டமைக்க இந்த குறியீட்டைப் பயன்படுத்தவும்`,
        emergencyMsg: `is riding in has reached you because of some emergency, you can track his ride here`,
        resetpassword: `உங்கள் கடவுச்சொல் மீட்டமைக்கப்பட்டது. நன்றி.`,
        proofStatus: `உங்கள் கணக்கு செயல்படுத்தப்பட்டது. நன்றி.`,
        rideLaterReceived: `Your Ride Later request received,we will assign Driver before Trip Time.`,
        inactivateIdelDriver: `உங்கள் நிலை ஆஃப்லைனில் உள்ளது. தயவுசெய்து அதை 'ஆன்லைனில்' மாற்றவும்.`,
        rideLaterNoResponse: `Your Scheduled Trip has cancelled due to Driver unavailablity, you can request later.`,
    },
    hi: {
        testMsg: `Hi, Test Push Notification From `,
        tripEnd: `यात्रा(ट्रिप) पहले से समाप्त किया गया`,
        driver: `Your Driver Has Arived`,
        tripstart: `Trip Started`,
        acceptScheduleRequest: `Driver Has Accepted Your Schedule Trip Request`,
        driverCancelScheduleTaxi: `Schedule Trip Cancelled By Driver`,
        userCancelScheduleTaxi: `राइडर द्वारा अनुसूचित यात्रा रद्द कर दिया गया`,
        acceptRequest: `Driver Has Accepted Your Trip Request`,
        requestTaxiRetry: `Trip Cancelled By Driver`,
        cancelCurrentTrip: `ट्रिप रद्द कर दी गई`,
        updateDropLocation: `Current Trip Drop Location Changed.`,
        sendSCHStartRequestToDrivers: `आपके पास इस समय पहले से ही एक अनुसूचित यात्रा है`,
        sendSCHStartAlertToRider: `आपके पास इस समय पहले से ही एक अनुसूचित यात्रा है`,
        sendnotification: `आपके पास एक आगामी अनुसूचित यात्रा है `,
        sendrequest: `Safe Taxi Request`,
        newquest: `नया निवेदन`,
        updateDriver: `नया निवेदन`,
        test: `RebuStar app`,
        verifyNumberRider: `के लिए आपका ओटीपी सत्यापन कोड `,
        forgotPasswordRider: `अपना खाता पासवर्ड रीसेट करने के लिए इस कोड का उपयोग करें`,
        emergencyMsg: `is riding in has reached you because of some emergency, you can track his ride here`,
        resetpassword: `आपका पासवर्ड रीसेट कर दिया गया है। धन्यवाद।`,
        proofStatus: `आपका खाता सक्रिय हो गया है। धन्यवाद।`,
        rideLaterReceived: `Your Ride Later request received,we will assign Driver before Trip Time.`,
        inactivateIdelDriver: `आपका स्थिति(स्टेटस) ऑफलाइन हो गया है। कृपया इसे अपने ड्राइवर ऐप में ऑनलाइन करें।`,
        rideLaterNoResponse: `Your Scheduled Trip has cancelled due to Driver unavailablity, you can request later.`,
    },
}; module.exports = notifications